# coding: utf-8

"""
    APITUDE BOOKINGAPI

    BOOKINGAPI is designed to book hotels in real time as fast as in two steps. It covers the complete booking process; it allows generating lists of hotels, confirming bookings, getting lists of bookings, obtaining booking information, making cancellations and modify existing bookings.   BOOKINGAPI works in combination with CONTENTAPI to obtain content information from the hotels, such as pictures, description, facilities, services, etc. Please refer to the ContentAPI documentation and IO/DOCS for related information.    BOOKINGAPI has been designed for a two steps confirmation, but due the the complexity of client and providers systems a third method has been designed.

    OpenAPI spec version: 1.0
    Contact: apitude@hotelbeds.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .api_audit_data import ApiAuditData
from .api_billing_address import ApiBillingAddress
from .api_boards import ApiBoards
from .api_booking import ApiBooking
from .api_booking_device import ApiBookingDevice
from .api_booking_room import ApiBookingRoom
from .api_bookings import ApiBookings
from .api_cancellation_policy import ApiCancellationPolicy
from .api_cost import ApiCost
from .api_credit_card import ApiCreditCard
from .api_daily_rate import ApiDailyRate
from .api_destination import ApiDestination
from .api_error import ApiError
from .api_filter import ApiFilter
from .api_geo_location import ApiGeoLocation
from .api_holder import ApiHolder
from .api_hotel import ApiHotel
from .api_hotels import ApiHotels
from .api_hotels_filter import ApiHotelsFilter
from .api_keyword import ApiKeyword
from .api_keywords_filter import ApiKeywordsFilter
from .api_modification_policies import ApiModificationPolicies
from .api_occupancy import ApiOccupancy
from .api_offer import ApiOffer
from .api_pax import ApiPax
from .api_payment_card import ApiPaymentCard
from .api_payment_contact_data import ApiPaymentContactData
from .api_payment_data import ApiPaymentData
from .api_promotion import ApiPromotion
from .api_rate import ApiRate
from .api_rate_break_down import ApiRateBreakDown
from .api_rate_discount import ApiRateDiscount
from .api_rate_supplement import ApiRateSupplement
from .api_review import ApiReview
from .api_review_filter import ApiReviewFilter
from .api_rooms import ApiRooms
from .api_shift_rate import ApiShiftRate
from .api_source import ApiSource
from .api_stay import ApiStay
from .api_supplier import ApiSupplier
from .api_tax import ApiTax
from .api_taxes import ApiTaxes
from .api_upselling import ApiUpselling
from .api_voucher import ApiVoucher
from .api_voucher_comment import ApiVoucherComment
from .api_voucher_email import ApiVoucherEmail
from .availability_rq import AvailabilityRQ
from .availability_rs import AvailabilityRS
from .booking_cancellation_rs import BookingCancellationRS
from .booking_change_rq import BookingChangeRQ
from .booking_change_rs import BookingChangeRS
from .booking_detail_rs import BookingDetailRS
from .booking_list_rs import BookingListRS
from .booking_rq import BookingRQ
from .booking_rs import BookingRS
from .check_rate_rq import CheckRateRQ
from .check_rate_rs import CheckRateRS
from .room import Room
from .status_rs import StatusRS
