# coding: utf-8

"""
    APITUDE BOOKINGAPI

    BOOKINGAPI is designed to book hotels in real time as fast as in two steps. It covers the complete booking process; it allows generating lists of hotels, confirming bookings, getting lists of bookings, obtaining booking information, making cancellations and modify existing bookings.   BOOKINGAPI works in combination with CONTENTAPI to obtain content information from the hotels, such as pictures, description, facilities, services, etc. Please refer to the ContentAPI documentation and IO/DOCS for related information.    BOOKINGAPI has been designed for a two steps confirmation, but due the the complexity of client and providers systems a third method has been designed.

    OpenAPI spec version: 1.0
    Contact: apitude@hotelbeds.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiBookingRoom(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rate_key': 'str',
        'pax': 'list[ApiPax]'
    }

    attribute_map = {
        'rate_key': 'rateKey',
        'pax': 'pax'
    }

    def __init__(self, rate_key=None, pax=None):
        """
        ApiBookingRoom - a model defined in Swagger
        """

        self._rate_key = None
        self._pax = None

        self.rate_key = rate_key
        if pax is not None:
          self.pax = pax

    @property
    def rate_key(self):
        """
        Gets the rate_key of this ApiBookingRoom.

        :return: The rate_key of this ApiBookingRoom.
        :rtype: str
        """
        return self._rate_key

    @rate_key.setter
    def rate_key(self, rate_key):
        """
        Sets the rate_key of this ApiBookingRoom.

        :param rate_key: The rate_key of this ApiBookingRoom.
        :type: str
        """
        if rate_key is None:
            raise ValueError("Invalid value for `rate_key`, must not be `None`")

        self._rate_key = rate_key

    @property
    def pax(self):
        """
        Gets the pax of this ApiBookingRoom.

        :return: The pax of this ApiBookingRoom.
        :rtype: list[ApiPax]
        """
        return self._pax

    @pax.setter
    def pax(self, pax):
        """
        Sets the pax of this ApiBookingRoom.

        :param pax: The pax of this ApiBookingRoom.
        :type: list[ApiPax]
        """

        self._pax = pax

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiBookingRoom):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
