# coding: utf-8

"""
    APITUDE BOOKINGAPI

    BOOKINGAPI is designed to book hotels in real time as fast as in two steps. It covers the complete booking process; it allows generating lists of hotels, confirming bookings, getting lists of bookings, obtaining booking information, making cancellations and modify existing bookings.   BOOKINGAPI works in combination with CONTENTAPI to obtain content information from the hotels, such as pictures, description, facilities, services, etc. Please refer to the ContentAPI documentation and IO/DOCS for related information.    BOOKINGAPI has been designed for a two steps confirmation, but due the the complexity of client and providers systems a third method has been designed.

    OpenAPI spec version: 1.0
    Contact: apitude@hotelbeds.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiBookings(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_from': 'int',
        'to': 'int',
        'total': 'float',
        'booking': 'list[ApiBooking]'
    }

    attribute_map = {
        '_from': 'from',
        'to': 'to',
        'total': 'total',
        'booking': 'booking'
    }

    def __init__(self, _from=None, to=None, total=None, booking=None):
        """
        ApiBookings - a model defined in Swagger
        """

        self.__from = None
        self._to = None
        self._total = None
        self._booking = None

        if _from is not None:
          self._from = _from
        if to is not None:
          self.to = to
        if total is not None:
          self.total = total
        if booking is not None:
          self.booking = booking

    @property
    def _from(self):
        """
        Gets the _from of this ApiBookings.

        :return: The _from of this ApiBookings.
        :rtype: int
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """
        Sets the _from of this ApiBookings.

        :param _from: The _from of this ApiBookings.
        :type: int
        """

        self.__from = _from

    @property
    def to(self):
        """
        Gets the to of this ApiBookings.

        :return: The to of this ApiBookings.
        :rtype: int
        """
        return self._to

    @to.setter
    def to(self, to):
        """
        Sets the to of this ApiBookings.

        :param to: The to of this ApiBookings.
        :type: int
        """

        self._to = to

    @property
    def total(self):
        """
        Gets the total of this ApiBookings.

        :return: The total of this ApiBookings.
        :rtype: float
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this ApiBookings.

        :param total: The total of this ApiBookings.
        :type: float
        """

        self._total = total

    @property
    def booking(self):
        """
        Gets the booking of this ApiBookings.

        :return: The booking of this ApiBookings.
        :rtype: list[ApiBooking]
        """
        return self._booking

    @booking.setter
    def booking(self, booking):
        """
        Sets the booking of this ApiBookings.

        :param booking: The booking of this ApiBookings.
        :type: list[ApiBooking]
        """

        self._booking = booking

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiBookings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
