# coding: utf-8

"""
    APITUDE BOOKINGAPI

    BOOKINGAPI is designed to book hotels in real time as fast as in two steps. It covers the complete booking process; it allows generating lists of hotels, confirming bookings, getting lists of bookings, obtaining booking information, making cancellations and modify existing bookings.   BOOKINGAPI works in combination with CONTENTAPI to obtain content information from the hotels, such as pictures, description, facilities, services, etc. Please refer to the ContentAPI documentation and IO/DOCS for related information.    BOOKINGAPI has been designed for a two steps confirmation, but due the the complexity of client and providers systems a third method has been designed.

    OpenAPI spec version: 1.0
    Contact: apitude@hotelbeds.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiVoucherEmail(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'to': 'str',
        '_from': 'str',
        'title': 'str',
        'body': 'str'
    }

    attribute_map = {
        'to': 'to',
        '_from': 'from',
        'title': 'title',
        'body': 'body'
    }

    def __init__(self, to=None, _from=None, title=None, body=None):
        """
        ApiVoucherEmail - a model defined in Swagger
        """

        self._to = None
        self.__from = None
        self._title = None
        self._body = None

        if to is not None:
          self.to = to
        if _from is not None:
          self._from = _from
        if title is not None:
          self.title = title
        if body is not None:
          self.body = body

    @property
    def to(self):
        """
        Gets the to of this ApiVoucherEmail.

        :return: The to of this ApiVoucherEmail.
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """
        Sets the to of this ApiVoucherEmail.

        :param to: The to of this ApiVoucherEmail.
        :type: str
        """

        self._to = to

    @property
    def _from(self):
        """
        Gets the _from of this ApiVoucherEmail.

        :return: The _from of this ApiVoucherEmail.
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """
        Sets the _from of this ApiVoucherEmail.

        :param _from: The _from of this ApiVoucherEmail.
        :type: str
        """

        self.__from = _from

    @property
    def title(self):
        """
        Gets the title of this ApiVoucherEmail.

        :return: The title of this ApiVoucherEmail.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this ApiVoucherEmail.

        :param title: The title of this ApiVoucherEmail.
        :type: str
        """

        self._title = title

    @property
    def body(self):
        """
        Gets the body of this ApiVoucherEmail.

        :return: The body of this ApiVoucherEmail.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """
        Sets the body of this ApiVoucherEmail.

        :param body: The body of this ApiVoucherEmail.
        :type: str
        """

        self._body = body

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiVoucherEmail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
