# coding: utf-8

"""
    APITUDE BOOKINGAPI

    BOOKINGAPI is designed to book hotels in real time as fast as in two steps. It covers the complete booking process; it allows generating lists of hotels, confirming bookings, getting lists of bookings, obtaining booking information, making cancellations and modify existing bookings.   BOOKINGAPI works in combination with CONTENTAPI to obtain content information from the hotels, such as pictures, description, facilities, services, etc. Please refer to the ContentAPI documentation and IO/DOCS for related information.    BOOKINGAPI has been designed for a two steps confirmation, but due the the complexity of client and providers systems a third method has been designed.

    OpenAPI spec version: 1.0
    Contact: apitude@hotelbeds.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiModificationPolicies(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cancellation': 'bool',
        'modification': 'bool'
    }

    attribute_map = {
        'cancellation': 'cancellation',
        'modification': 'modification'
    }

    def __init__(self, cancellation=False, modification=False):
        """
        ApiModificationPolicies - a model defined in Swagger
        """

        self._cancellation = None
        self._modification = None

        self.cancellation = cancellation
        self.modification = modification

    @property
    def cancellation(self):
        """
        Gets the cancellation of this ApiModificationPolicies.

        :return: The cancellation of this ApiModificationPolicies.
        :rtype: bool
        """
        return self._cancellation

    @cancellation.setter
    def cancellation(self, cancellation):
        """
        Sets the cancellation of this ApiModificationPolicies.

        :param cancellation: The cancellation of this ApiModificationPolicies.
        :type: bool
        """
        if cancellation is None:
            raise ValueError("Invalid value for `cancellation`, must not be `None`")

        self._cancellation = cancellation

    @property
    def modification(self):
        """
        Gets the modification of this ApiModificationPolicies.

        :return: The modification of this ApiModificationPolicies.
        :rtype: bool
        """
        return self._modification

    @modification.setter
    def modification(self, modification):
        """
        Sets the modification of this ApiModificationPolicies.

        :param modification: The modification of this ApiModificationPolicies.
        :type: bool
        """
        if modification is None:
            raise ValueError("Invalid value for `modification`, must not be `None`")

        self._modification = modification

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiModificationPolicies):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
