# coding: utf-8

"""
    APITUDE BOOKINGAPI

    BOOKINGAPI is designed to book hotels in real time as fast as in two steps. It covers the complete booking process; it allows generating lists of hotels, confirming bookings, getting lists of bookings, obtaining booking information, making cancellations and modify existing bookings.   BOOKINGAPI works in combination with CONTENTAPI to obtain content information from the hotels, such as pictures, description, facilities, services, etc. Please refer to the ContentAPI documentation and IO/DOCS for related information.    BOOKINGAPI has been designed for a two steps confirmation, but due the the complexity of client and providers systems a third method has been designed.

    OpenAPI spec version: 1.0
    Contact: apitude@hotelbeds.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CheckRateRQ(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'echo_token': 'str',
        'upselling': 'bool',
        'language': 'str',
        'rooms': 'list[ApiBookingRoom]'
    }

    attribute_map = {
        'echo_token': 'echoToken',
        'upselling': 'upselling',
        'language': 'language',
        'rooms': 'rooms'
    }

    def __init__(self, echo_token=None, upselling=False, language=None, rooms=None):
        """
        CheckRateRQ - a model defined in Swagger
        """

        self._echo_token = None
        self._upselling = None
        self._language = None
        self._rooms = None

        if echo_token is not None:
          self.echo_token = echo_token
        if upselling is not None:
          self.upselling = upselling
        if language is not None:
          self.language = language
        self.rooms = rooms

    @property
    def echo_token(self):
        """
        Gets the echo_token of this CheckRateRQ.

        :return: The echo_token of this CheckRateRQ.
        :rtype: str
        """
        return self._echo_token

    @echo_token.setter
    def echo_token(self, echo_token):
        """
        Sets the echo_token of this CheckRateRQ.

        :param echo_token: The echo_token of this CheckRateRQ.
        :type: str
        """

        self._echo_token = echo_token

    @property
    def upselling(self):
        """
        Gets the upselling of this CheckRateRQ.

        :return: The upselling of this CheckRateRQ.
        :rtype: bool
        """
        return self._upselling

    @upselling.setter
    def upselling(self, upselling):
        """
        Sets the upselling of this CheckRateRQ.

        :param upselling: The upselling of this CheckRateRQ.
        :type: bool
        """

        self._upselling = upselling

    @property
    def language(self):
        """
        Gets the language of this CheckRateRQ.

        :return: The language of this CheckRateRQ.
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """
        Sets the language of this CheckRateRQ.

        :param language: The language of this CheckRateRQ.
        :type: str
        """

        self._language = language

    @property
    def rooms(self):
        """
        Gets the rooms of this CheckRateRQ.

        :return: The rooms of this CheckRateRQ.
        :rtype: list[ApiBookingRoom]
        """
        return self._rooms

    @rooms.setter
    def rooms(self, rooms):
        """
        Sets the rooms of this CheckRateRQ.

        :param rooms: The rooms of this CheckRateRQ.
        :type: list[ApiBookingRoom]
        """
        if rooms is None:
            raise ValueError("Invalid value for `rooms`, must not be `None`")

        self._rooms = rooms

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CheckRateRQ):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
